### ISSUE TITLE
Data optimization epic

### ISSUE THREAD

**Issue by AndreiBarsan** [pit30m/pit30m#54]
Important but non-blocking things to improve in the bucket. That is, improvements which _need_ bucket writes. Of course, this covers known things. Once users start utilizing our dataset, it is likely they will uncover small issues and possible improvements we will also need write access to update.

 - [ ] optimize LiDAR to non-redundant vehicle-relative f32
 - [ ] pre-cache a log's camera metadata into single npy file
 - [ ] optimize calibration files to be more self-contained (right now they are usable but require complicated software work), especially `raw_calibration.yml`
 - [ ] clean up and re-upload vehicle data time series (e.g., engine state, etc.)
 - [ ] upload weather metadata
