### ISSUE TITLE
Data cleaning epic

### ISSUE THREAD

**Issue by AndreiBarsan** [pit30m/pit30m#58]
- [ ] Delete v0 indexes (safe once NetVLAD prototype validated)
 - [ ] Delete v1 indexes (safe once NetVLAD prototype validated)
 - [ ] Delete old LiDAR (once optimized LiDAR in place)
